services:
  node:
    image: node:latest
    container_name: node
    hostname: node_enviroment
    ports: 
      - 3000:3000
      - 9229:9229
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: tail -f /dev/null