services:
  node:
    image: node:latest
    container_name: node
    hostname: node_enviroment
    ports: 
      - 3000:3000
      - 9229:9229
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: su -c "npx nodemon --inspect-brk --legacy-watch --inspect=0.0.0.0:9229 index.js 2> /dev/null | npx nodemon index.js"